DROP TABLE IF EXISTS dogs;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS singers;
DROP TABLE IF EXISTS cars;

CREATE TABLE dogs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  type TEXT NOT NULL
);

CREATE TABLE people (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  born TEXT NOT NULL,
  died TEXT NOT NULL
);

CREATE TABLE singers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  realname TEXT NOT NULL
);

CREATE TABLE cars (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  car TEXT NOT NULL,
  color TEXT NOT NULL,
  year INTEGER NOT NULL
);

